services:
  mxrr-dev:
    image: kareigu/karei-dev:new
    container_name: karei-dev
    restart: unless-stopped
    ports:
      - 3030:3030
    volumes:
      - ./pagedata:/go/src/mxrr-dev/pagedata
      - ./files:/go/src/mxrr-dev/files
      - ./logs:/go/src/mxrr-dev/logs
      - ./certs:/go/src/mxrr-dev/certs