services:
  mxrr-dev:
    image: mxr/mxrr-dev:new
    container_name: mxrr-dev
    restart: unless-stopped
    ports:
      - 2000:2000
    volumes:
      - ./pagedata:/go/src/mxrr-dev/pagedata
      - ./files:/go/src/mxrr-dev/files
      - ./logs:/go/src/mxrr-dev/logs