name: Build

on:
  pull_request:
    branches: [ prod ]

  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build docker image
        run: make docker
